// felica_error.h -*-c++-*-
// FeliCa Access Library Error Types
// Copyright 2007 Sony Imaging Products & Solutions Inc.

// [CAUTION] This file is automatically generated. Do not edit this file.

#ifndef FELICA_ERROR_H
#define FELICA_ERROR_H

#ifdef __cplusplus
enum enumeration_felica_error_type {
#else if
typedef enum enumeration_felica_error_type_T {
#endif
    FELICA_ERROR_NOT_OCCURRED = 1000,                                  // エラーは発生していません (0x3e8)
    FELICA_UNKNOWN_ERROR = 1001,                                       // 未定義のエラーです (0x3e9)
    FELICA_ILLEGAL_ARGUMENT = 1002,                                    // 関数の引数が不正です (0x3ea)
    FELICA_MEMORY_ALLOCATION_ERROR = 1003,                             // メモリの確保ができません (0x3eb)
    FELICA_THREAD_CREATION_ERROR = 1004,                               // スレッドの生成に失敗しました (0x3ec)
    FELICA_LIBRARY_NOT_INITIALIZED = 1005,                             // ライブラリが初期化されていません (0x3ed)
    FELICA_LIBRARY_ALREADY_INITIALIZED = 1006,                         // ライブラリは既に初期化されています (0x3ee)
    FELICA_INVALID_FILE_NAME = 1007,                                   // 不正なファイル名が指定されました (0x3ef)
    FELICA_FILE_NOT_FOUND = 1008,                                      // ファイルを見つけることができません (0x3f0)
    FELICA_FILE_OPEN_ERROR = 1009,                                     // ファイルをオープンすることができません (0x3f1)
    FELICA_FILE_NOT_OPENED = 1010,                                     // ファイルがオープンされていません (0x3f2)
    FELICA_FILE_ALREADY_OPENED = 1011,                                 // ファイルは既にオープンされています (0x3f3)
    FELICA_INVALID_DIRECTORY_NAME = 1012,                              // 不正なディレクトリ名が指定されました (0x3f4)
    FELICA_DIRECTORY_NOT_FOUND = 1013,                                 // ディレクトリを見つけることができません (0x3f5)
    FELICA_DIRECTORY_OPEN_ERROR = 1014,                                // ディレクトリをオープンすることができません (0x3f6)
    FELICA_DIRECTORY_NOT_OPENED = 1015,                                // ディレクトリがオープンされていません (0x3f7)
    FELICA_DIRECTORY_ALREADY_OPENED = 1016,                            // ディレクトリは既にオープンされています (0x3f8)
    FELICA_INVALID_COMMUNICATIONS_PORT_NAME = 1017,                    // 不正なポート名が指定されました (0x3f9)
    FELICA_COMMUNICATIONS_PORT_NOT_FOUND = 1018,                       // ポートを見つけることができません (0x3fa)
    FELICA_COMMUNICATIONS_PORT_OPEN_ERORR = 1019,                      // ポートをオープンすることができません (0x3fb)
    FELICA_COMMUNICATIONS_PORT_NOT_OPENED = 1020,                      // ポートがオープンされていません (0x3fc)
    FELICA_COMMUNICATIONS_PORT_ALREADY_OPENED = 1021,                  // ポートは既にオープンされています (0x3fd)
    FELICA_INVALID_TIME_OUT = 1022,                                    // タイムアウトの値が不正です (0x3fe)
    FELICA_INVALID_BAUD_RATE = 1023,                                   // ボーレートの値が不正です (0x3ff)
    FELICA_INVALID_RETRY_COUNT = 1024,                                 // リトライカウントの値が不正です (0x400)
    FELICA_READER_WRITER_CONTROL_LIBRARY_NOT_FOUND = 1025,             // FeliCa リーダ／ライタコントロールライブラリを見つけることができません (0x401)
    FELICA_READER_WRITER_CONTROL_LIBRARY_LOAD_ERROR = 1026,            // FeliCa リーダ／ライタコントロールライブラリのロードに失敗しました (0x402)
    FELICA_READER_WRITER_OPEN_ERROR = 1027,                            // リーダ／ライタのオープンに失敗しました (0x403)
    FELICA_READER_WRITER_OPEN_AUTO_ERROR = 1028,                       // リーダ／ライタを自動認識できません (0x404)
    FELICA_READER_WRITER_NOT_OPENED = 1029,                            // リーダ／ライタがオープンされていません (0x405)
    FELICA_READER_WRITER_ALREADY_OPENED = 1030,                        // リーダ／ライタは既にオープンされています (0x406)
    FELICA_READER_WRITER_RECONNECT_ERROR = 1031,                       // リーダ／ライタとの再接続に失敗しました (0x407)
    FELICA_MESSAGE_OF_CARD_FIND_REGISTRATION_ERROR = 1032,             // カードがかざされたときに送信するメッセージの登録に失敗しました (0x408)
    FELICA_MESSAGE_OF_CARD_LOSS_REGISTRATION_ERROR = 1033,             // カードを見失なったときに送信するメッセージの登録に失敗しました (0x409)
    FELICA_CALL_BACK_PARAMETERS_NOT_SETTED = 1034,                     // コールバックパラメータが設定されていません (0x40a)
    FELICA_SUCCESSIVE_POLLING_FOR_CALL_BACK_NOT_STARTED = 1035,        // コールバックを行うための連続ポーリングが開始されていません (0x40b)
    FELICA_POLLING_ERROR = 1036,                                       // ポーリングに失敗しました (0x40c)
    FELICA_REQUEST_RESPONSE_ERROR = 1037,                              // カードのモードの取得に失敗しました (0x40d)
    FELICA_REQUEST_SERVICE_ERROR = 1038,                               // カードのエリア・サービスキーバージョンの取得に失敗しました (0x40e)
    FELICA_MUTUAL_AUTHENTICATION_ERROR = 1039,                         // カードとの相互認証に失敗しました (0x40f)
    FELICA_READ_BLOCK_ERROR = 1040,                                    // カードからのデータの読み込みに失敗しました (0x410)
    FELICA_WRITE_BLOCK_ERROR = 1041,                                   // カードへのデータの書き込みに失敗しました (0x411)
    FELICA_READ_BLOCK_WITHOUT_ENCRYPTION_ERROR = 1042,                 // カードからの鍵のないサービスデータの読み込みに失敗しました (0x412)
    FELICA_WRITE_BLOCK_WIHTOUT_ENCRYPTION_ERROR = 1043,                // カードへの鍵のないサービスデータの書き込みに失敗しました (0x413)
    FELICA_DUMB_ERROR = 1044,                                          // コミュニケートスルーコマンドの発行に失敗しました (0x414)
    FELICA_MAKE_ACCESS_KEYS_ERROR = 1045,                              // アクセスキーの生成に失敗しました (0x415)
    FELICA_CARD_INFORMATION_NOT_FOUND = 1046,                          // まだ一度もポーリングが行われていません (0x416)
    FELICA_CARD_INFORMATION_ACCESS_ERROR = 1047,                       // カードの情報の取得に失敗しました (0x417)
    FELICA_INVALID_CARD_INDEX = 1048,                                  // カードのインデックスが不正なためカードの情報を取得できませんでした (0x418)
    FELICA_CARD_IDM_UNMATCHED = 1049,                                  // ポーリングの時に取得したカード IDm と関数引数のカード IDm が一致しなかったため処理を中断しました (0x419)
    FELICA_MUTUAL_AUTHENTICATION_NOT_DONE = 1050,                      // 相互認証が行われていません (0x41a)
    FELICA_ILLEGAL_SERVICE_SETTED = 1051,                              // 鍵のないサービスへの読み書きに相互認証が必要なサービスが指定されました (0x41b)
    FELICA_BLOCK_LIST_GENERATION_ERROR = 1052,                         // ブロックリストを自動生成することができないサービス (Cash Back and Decrement) が指定されました (0x41c)
    FELICA_ACCESS_LIBRARY_FUNCTION_ERROR = 1053,                       // FeliCa アクセスライブラリの API の呼び出しに失敗しました (0x41d)
    FELICA_EXCHANGE_KEY_ERROR = 1054,                                  // 鍵の変更に失敗しました (0x41e)
    FELICA_SUCCESSIVE_POLLING_FOR_CALL_BACK_ALREADY_STARTED = 1055,    // 連続ポーリングはすでに起動しています (0x41f)
    FELICA_MESSAGE_OF_READER_WRITER_CONNECT_REGISTRATION_ERROR = 1056, // リーダライタが接続されたときに送信するメッセージ登録に失敗しました (0x420)
    FELICA_MESSAGE_OF_READER_WRITER_PULLOUT_REGISTRATION_ERROR = 1057, // リーダライタが抜かれたときに送信するメッセージ登録に失敗しました (0x421)
    FELICA_PLUG_AND_PLAY_WATCH_FOR_CALL_BACK_NOT_STARTED = 1058,       // プラグアンドプレイ監視は起動していません (0x422)
    FELICA_PLUG_AND_PLAY_WATCH_FOR_CALL_BACK_ALREADY_STARTED = 1059,   // プラグアンドプレイ監視はすでに起動しています (0x423)
    FELICA_API_NOT_IMPLEMENTED_FOR_THIS_PLATFORM = 1060,               // この OS では実装されていいない API です (0x424)
    FELICA_API_NOT_IMPLEMENTED_FOR_THIS_PLATHOME
           = FELICA_API_NOT_IMPLEMENTED_FOR_THIS_PLATFORM,             // この OS では実装されていない API です (0x424) 
    FELICA_REQUEST_SYSTEM_CODE_ERROR = 1061,                           // カードのシステムコードリストの取得に失敗しました (0x425)
    FELICA_SEARCH_SERVICE_CODE_ERROR = 1062,                           // カードのサービスコードリストの取得に失敗しました (0x426)
    FELICA_APPEND_KEY_LIST_TO_ACCESS_KEYS_ERROR = 1063,                // アクセスキーへのキーの追加に失敗しました (0x427)
    FELICA_SET_SHARED_OPEN_MODE_ERROR = 1064,                          // オープンモードの設定に失敗しました (0x428)
    FELICA_TRANSACTION_LOCK_ERROR = 1065,                              // アクセス権獲得（ロック）に失敗しました (0x429)
    FELICA_TRANSACTION_UNLOCK_ERROR = 1066,                            // アクセス権解放（アンロック）に失敗しました (0x42a)
    FELICA_SET_LOCK_TIMEOUT_ERROR = 1067,                              // アクセス権解放待ちタイムアウト設定に失敗しました (0x42b)
    FELICA_GET_LOCK_TIMEOUT_ERROR = 1068,                              // アクセス権解放待ちタイムアウト取得に失敗しました (0x42c)
    FELICA_GET_DEVICE_INFO_FAILED = 1069,                              // デバイス情報取得に失敗しました (0x42d)
    FELICA_GET_OPEN_PROCCESS_COUNT_FAILED = 1070,                      // 共有プロセス数の取得に失敗しました (0x42e)
    FELICA_GET_OPEN_PROCCESS_COUNT_FAILD 
    		= FELICA_GET_OPEN_PROCCESS_COUNT_FAILED,				   // 共有プロセス数の取得に失敗しました (0x42e)
    FELICA_SET_POLLING_TIMEOUT_ERROR = 1071,                           // ポーリングタイムアウト設定に失敗しました (0x42f)
    FELICA_GET_POLLING_TIMEOUT_ERROR = 1072,                           // ポーリングタイムアウト取得に失敗しました (0x430)
    FELICA_CHANGE_PARAMETER_ERROR = 1073,                              // リーダ／ライタの設定変更に失敗しました (0x431)
    FELICA_GET_LAST_ERROR_ERROR = 1074,                                // リーダ／ライタから最新のエラーコードが取得できませんでした (0x432)
    FELICA_GET_ATTRIBUTE_ERROR = 1075,                                 // リーダ／ライタから属性情報が取得できませんでした (0x433)
    FELICA_COMMUNICATE_THRU_ERROR = 1076,                              // Communicate Thruコマンドの実行に失敗しました (0x434)
    FELICA_RF_SWITCH_ERROR = 1077,                                     // RF Switch のON/OFFの設定に失敗しました (0x435)
    FELICA_REQUEST_BLOCK_INFO_EX_ERROR = 1078,                         // 空きブロック数の取得に失敗しました (0x436)
    FELICA_GET_CONTAINER_ISSUE_INFO_ERROR = 1079,                      // コンテナ発行情報の取得に失敗しました (0x437)
    FELICA_SET_REL_SERVICE_PACKAGE_ERROR = 1080,                       // 認証連携の設定に失敗しました (0x438)
    FELICA_FALP_OPENED = 1081,                                         // FALPモードのため処理できません (0x439)
    FELICA_FALP_NOT_OPENED = 1082,                                     // FALPモードではありません (0x43a)
    FELICA_FALP_LIBRARY_ERROR = 1083,                                  // FALPライブラリでエラーが発生しました (0x43b)
    FELICA_FALP_LIBRARY_INITIALIZE_ERROR = 1084,                       // FALPライブラリの初期化に失敗しました (0x43c)
    FELICA_FALP_LIBRARY_LOAD_ERROR = 1085,                             // FALPライブラリのロードに失敗しました (0x43d)
    FELICA_GET_SEQUENSE_NUMBER_ERROR = 1086,                           // シーケンス番号の取得に失敗しました (0x43e)
    FELICA_ILLEGAL_ARGUMENT_ON_CURRENT_CODE_LENGTH_MODE = 1087,        // 現在のノードコード長では処理できません (0x43f)
    FELICA_LIBRARY_IS_INVALID = 1088,                                  // FeliCaライブラリファイルが不正です (0x440)
	FELICA_FALP_TARGET_WAIT_MODE = 1089,							   // 既にターゲット接続待ち要求が発行されています(0x441)
	FELICA_FALP_NOT_TARGET_WAIT_MODE = 1090,						   // ターゲット接続待ち要求を発行していません(0x442)
	FELICA_FALP_CALL_BACK_PARAMETERS_NOT_SET = 1091,				   // FALPターゲット用コールバックパラメータが設定されていません(0x443)
	FELICA_FALP_TARGET_MODE = 1092,									   // FALPターゲットモードのため処理できません(0x444)
	FELICA_FALP_NOT_TARGET_MODE = 1093,								   // FALPターゲットモードではありません(0x445)
	FELICA_FALP_TARGET_TRANSMIT_MODE = 1094,						   // FALPターゲットデータ転送中のため処理できません(0x446)
	FELICA_FALP_TARGET_TARNSMIT_MODE = 
			FELICA_FALP_TARGET_TRANSMIT_MODE,
	FELICA_READ_REGISTER_ERROR = 1095,								   // レジスタのリードに失敗しました(0x447)
	FELICA_SOFT_RESET_ERROR = 1097									   // ソフトリセットに失敗しました(0x449)

#ifdef __cplusplus
};
#else if
}enumeration_felica_error_type;
#endif


/*
1000 = エラーは発生していません
1001 = 未定義のエラーです
1002 = 関数の引数が不正です
1003 = メモリの確保ができません
1004 = スレッドの生成に失敗しました
1005 = ライブラリが初期化されていません
1006 = ライブラリは既に初期化されています
1007 = 不正なファイル名が指定されました
1008 = ファイルを見つけることができません
1009 = ファイルをオープンすることができません
1010 = ファイルがオープンされていません
1011 = ファイルは既にオープンされています
1012 = 不正なディレクトリ名が指定されました
1013 = ディレクトリを見つけることができません
1014 = ディレクトリをオープンすることができません
1015 = ディレクトリがオープンされていません
1016 = ディレクトリは既にオープンされています
1017 = 不正なポート名が指定されました
1018 = ポートを見つけることができません
1019 = ポートをオープンすることができません
1020 = ポートがオープンされていません
1021 = ポートは既にオープンされています
1022 = タイムアウトの値が不正です
1023 = ボーレートの値が不正です
1024 = リトライカウントの値が不正です
1025 = FeliCa リーダ／ライタコントロールライブラリを見つけることができません
1026 = FeliCa リーダ／ライタコントロールライブラリのロードに失敗しました
1027 = リーダ／ライタのオープンに失敗しました
1028 = リーダ／ライタを自動認識できません
1029 = リーダ／ライタがオープンされていません
1030 = リーダ／ライタは既にオープンされています
1031 = リーダ／ライタとの再接続に失敗しました
1032 = カードがかざされたときに送信するメッセージの登録に失敗しました
1033 = カードを見失なったときに送信するメッセージの登録に失敗しました
1034 = コールバックパラメータが設定されていません
1035 = コールバックを行うための連続ポーリングが開始されていません
1036 = ポーリングに失敗しました
1037 = カードのモードの取得に失敗しました
1038 = カードのエリア・サービスキーバージョンの取得に失敗しました
1039 = カードとの相互認証に失敗しました
1040 = カードからのデータの読み込みに失敗しました
1041 = カードへのデータの書き込みに失敗しました
1042 = カードからの鍵のないサービスデータの読み込みに失敗しました
1043 = カードへの鍵のないサービスデータの書き込みに失敗しました
1044 = コミュニケートスルーコマンドの発行に失敗しました
1045 = アクセスキーの生成に失敗しました
1046 = まだ一度もポーリングが行われていません
1047 = カードの情報の取得に失敗しました
1048 = カードのインデックスが不正なためカードの情報を取得できませんでした
1049 = ポーリングの時に取得したカード IDm と関数引数のカード IDm が一致しなかったため処理を中断しました
1050 = 相互認証が行われていません
1051 = 鍵のないサービスへの読み書きに相互認証が必要なサービスが指定されました
1052 = ブロックリストを自動生成することができないサービス (Cash Back and Decrement) が指定されました
1053 = FeliCa アクセスライブラリの API の呼び出しに失敗しました
1054 = 鍵の変更に失敗しました
1055 = 連続ポーリングはすでに起動しています
1056 = リーダライタが接続されたときに送信するメッセージ登録に失敗しました
1057 = リーダライタが抜かれたときに送信するメッセージ登録に失敗しました
1058 = プラグアンドプレイ監視は起動していません
1059 = プラグアンドプレイ監視はすでに起動しています
1060 = この OS では実装されていいない API です
1061 = カードのシステムコードリストの取得に失敗しました
1062 = カードのサービスコードリストの取得に失敗しました
1063 = アクセスキーへのキーの追加に失敗しました
1064 = オープンモードの設定に失敗しました
1065 = アクセス権獲得（ロック）に失敗しました
1066 = アクセス権解放（アンロック）に失敗しました
1067 = アクセス権解放待ちタイムアウト設定に失敗しました
1068 = アクセス権解放待ちタイムアウト取得に失敗しました
1069 = デバイス情報取得に失敗しました
1070 = 共有プロセス数の取得に失敗しました
1071 = ポーリングタイムアウト設定に失敗しました
1072 = ポーリングタイムアウト取得に失敗しました
1073 = リーダ／ライタの設定変更に失敗しました
1074 = リーダ／ライタから最新のエラーコードが取得できませんでした
1075 = リーダ／ライタから属性情報が取得できませんでした
1076 = Communicate Thruコマンドの実行に失敗しました
1077 = RF Switch のON/OFFの設定に失敗しました
1078 = 空きブロック数の取得に失敗しました
1079 = コンテナ発行情報の取得に失敗しました
1080 = 認証連携の設定に失敗しました
1081 = FALPモードのため処理できません
1082 = FALPモードではありません
1083 = FALPライブラリでエラーが発生しました
1084 = FALPライブラリの初期化に失敗しました
1085 = FALPライブラリのロードに失敗しました
1086 = シーケンス番号の取得に失敗しました
1087 = 現在のノードコード長では処理できません
1088 = FeliCaライブラリファイルが不正です
1089 = 既にターゲット接続待ち要求が発行されています
1090 = ターゲット接続待ち要求を発行していません
1091 = FALPターゲット用コールバックパラメータが設定されていません
1092 = FALPターゲットモードのため処理できません
1093 = FALPターゲットモードではありません
1094 = FALPターゲットデータ転送中のため処理できません
1095 = レジスタのリードに失敗しました
1097 = ソフトリセットに失敗しました
*/

typedef enumeration_felica_error_type enumernation_felica_error_type;

#endif // FELICA_ERROR_H
