// felica.h -*-c++-*-
// FeliCa Access Library
// Copyright 2006,2013 Sony Imaging Products & Solutions Inc.

// [CAUTION] This file is automatically generated. Do not edit this file.

#ifndef __FELICA_H__
#define __FELICA_H__

#include "felica_basic_lite_s.h"

#endif // __FELICA_H__
