// rw_error.h -*-c++-*-
// FeliCa Reader Writer Control Library Error Types
// Copyright 2004,2005,2006,2007 Sony Imaging Products & Solutions Inc.

// [CAUTION] This file is automatically generated. Do not edit this file.

#ifndef RW_ERROR_H
#define RW_ERROR_H

#ifdef __cplusplus
enum enumeration_rw_error_type {
#else if
typedef enum enumeration_rw_error_type_T {
#endif
    RW_ERROR_NOT_OCCURRED = 100,                                  // Error has not occurred. (0x64)
    RW_UNKNOWN_ERROR = 101,                                       // Undefined error (0x65)
    RW_ILLEGAL_ARGUMENT = 102,                                    // Argument of the function is illegal. (0x66)
    RW_MEMORY_ALLOCATION_ERROR = 103,                             // Cannot secure the memory space. (0x67)
    RW_THREAD_CREATION_ERROR = 104,                               // Failed in creating the thread. (0x68)
    RW_LIBRARY_NOT_INITIALIZED = 105,                             // The library is not initialized. (0x69)
    RW_LIBRARY_ALREADY_INITIALIZED = 106,                         // The library is already initialized. (0x6a)
    RW_INVALID_FILE_NAME = 107,                                   // An illegal name is specified. (0x6b)
    RW_FILE_NOT_FOUND = 108,                                      // Cannot find the file. (0x6c)
    RW_FILE_OPEN_ERROR = 109,                                     // Cannot open the file. (0x6d)
    RW_FILE_NOT_OPENED = 110,                                     // The file is not opened yet. (0x6e)
    RW_FILE_ALREADY_OPENED = 111,                                 // The file is already opened. (0x6f)
    RW_INVALID_DIRECTORY_NAME = 112,                              // An illegal directory name is specified. (0x70)
    RW_DIRECTORY_NOT_FOUND = 113,                                 // Cannot find the directory. (0x71)
    RW_DIRECTORY_OPEN_ERROR = 114,                                // Cannot open the directory, (0x72)
    RW_DIRECTORY_NOT_OPENED = 115,                                // The directory is not opened yet. (0x73)
    RW_DIRECTORY_ALREADY_OPENED = 116,                            // The directory is already opened. (0x74)
    RW_INVALID_COMMUNICATIONS_PORT_NAME = 117,                    // An illegal port name is specified. (0x75)
    RW_COMMUNICATIONS_PORT_NOT_FOUND = 118,                       // Cannot find the port. (0x76)
    RW_COMMUNICATIONS_PORT_OPEN_ERORR = 119,                      // Cannot open the port. (0x77)
    RW_COMMUNICATIONS_PORT_OPEN_ERROR = 119,                      // Cannot open the port. (0x77)
    RW_COMMUNICATIONS_PORT_NOT_OPENED = 120,                      // The port is not opened yet. (0x78)
    RW_COMMUNICATIONS_PORT_ALREADY_OPENED = 121,                  // The port is already opened. (0x79)
    RW_INVALID_TIME_OUT = 122,                                    // The time-out value is illegal. (0x7a)
    RW_INVALID_BAUD_RATE = 123,                                   // The baud rate value is illegal. (0x7b)
    RW_PLUGINS_HOME_DIRECTORY_NOT_SETTED = 124,                   // Home directory of plug-in is not set. (0x7c)
    RW_PLUGINS_HOME_DIRECTORY_NOT_FOUND = 125,                    // Cannot find the home directory of plug-in. (0x7d)
    RW_PLUGINS_INITIALIZE_ERROR = 126,                            // Failed in initializing the plug-in. (0x7e)
    RW_PLUGIN_NOT_FOUND = 127,                                    // Cannot find the plug-in. (0x7f)
    RW_COMMAND_PLUGIN_NOT_FOUND = 128,                            // Cannot find the command plug-in. (0x80)
    RW_DEVICE_PLUGIN_NOT_FOUND = 129,                             // Cannot find the device plug-in. (0x81)
    RW_UTILITY_PLUGIN_NOT_FOUND = 130,                               // Cannot find the utility plug-in. (0x82)
    RW_TABLE_ACCESS_ERROR = 131,                                  // Failed in accessing the table. (0x83)
    RW_COMMAND_NOT_FOUND = 132,                                   // Cannot find the command. (0x84)
    RW_SCRIPT_EXECUTION_ERROR = 133,                              // Failed in executing the script. (0x85)
    RW_COMMUNICATIONS_PORT_INITIALIZE_ERROR = 134,                // Failed in initializing the port. (0x86)
    RW_COMMUNICATIONAS_PORT_SET_TIME_OUT_ERROR = 135,             // Failed in setting time-out of the port. (0x87)
    RW_COMMUNICATIONS_PORT_SET_TIME_OUT_ERROR = 135,              // Failed in setting time-out of the port. (0x87)
    RW_ILLEGAL_COMMUNICATIONS_PORT_STATUS = 136,                  // Device control setup of the port is illegal. (0x88)
    RW_COMMUNICATIONS_PORT_MASKING_ERROR = 137,                   // Failed in masking the port. (0x89)
    RW_COMMUNICATIONAS_PORT_PURGING_ERROR = 138,                  // Failed in purging the port. (0x8a)
    RW_COMMUNICATIONS_PORT_PURGING_ERROR = 138,                   // Failed in purging the port. (0x8a)
    RW_PLAIN_DATA_LOAD_ERROR = 139,                               // Failed in acquisition of plain text data. (0x8b)
    RW_PLAIN_DATA_SAVE_ERROR = 140,                               // Failed in saving the plain text data. (0x8c)
    RW_CIPHER_DATA_LOAD_ERROR = 141,                              // Failed in acquisition of cipher text data. (0x8d)
    RW_CIPHER_DATA_SAVE_ERROR = 142,                              // Failed in saving the cipher text data. (0x8e)
    RW_RANDOM_NUMBER_NOT_SETTED = 143,                            // The random number sequence required for authentication is not set. (0x8f)
    RW_TRANSACTION_ID_NOT_SETTED = 144,                           // Transaction ID is not set. (0x90)
    RW_TRANSACTION_KEY_ACCESS_ERROR = 145,                        // Failed in acquiring the transaction key that is required for data encryption. (0x91)
    RW_ILLEGAL_TRANSACTION_KEY = 146,                             // The transaction key required for data encryption is illegal. (0x92)
    RW_COMMUNICATIONS_PARITY_ERROR = 147,                         // Un-matching is found in the communication parity check. (0x93)
    RW_NAK_RECEIVED = 148,                                        // Received NACK from the Reader/Writer. (0x94)
    RW_SYNTAX_ERROR = 149,                                        // Syntax error is notified from the Reader/Writer. (0x95)
    RW_ILLEGAL_PACKET_RECEIVED = 150,                             // Received illegal packet from Reader/Writer. (0x96)
    RW_SESSION_COUNT_OVER = 151,                                  // Number of times of sequence has exceeded what can be sent by a single session. (0x97)
    RW_RESPONSE_PACKET_NOT_RECEIVED = 152,                        // No response is returned from the Reader/Writer. (0x98)
    RW_DATA_SENDING_ERROR = 153,                                  // Failed in sending data to the Reader/Writer. (0x99)
    RW_DATA_SENDING_TIME_OUT = 154,                               // Time-out occurred when sending data to the Reader/Writer. (0x9a)
    RW_DATA_RECEIVING_ERROR = 155,                                // Failed in receiving data from the Reader/Writer. (0x9b)
    RW_DATA_RECEIVING_TIME_OUT = 156,                             // Time-out occurred when receiving data from the Reader/Writer. (0x9c)
    RW_CARD_NOT_FOUND = 157,                                      // Could not capture the card. (0x9d)
    RW_INVALID_CARD_INDEX = 158,                                  // Could not obtained the card information because of illegal index of the card. (0x9e)
    RW_CARD_STATUS_FLAG_ERROR = 159,                              // Received the error status flag from the card. (0x9f)
    RW_DUMB_RESPONSE_PACKET_NOT_RECEIVED = 160,                   // No response is returned to the Communicate Thru command. (0xa0)
    RW_USER_KEY_ERROR = 161,                                      // The method to specify the user key is incorrect (0xa1)
    RW_USER_KEY_EXPIRATION = 162,                                 // Duration of use is already expired (0xa2)
    RW_CALL_BACK_PARAMETERS_NOT_SETTED = 163,                     // Callback parameter is not set (0xa3)
    RW_MESSAGE_OF_READER_WRITER_CONNECT_REGISTRATION_ERROR = 164, // Failed to register the message that shall be sent when Reader/Writer is connected (0xa4)
    RW_MESSAGE_OF_READER_WRITER_PULLOUT_REGISTRATION_ERROR = 165, // Failed to register the message that shall be sent when Reader/Writer is disconnected (0xa5)
    RW_PLUG_AND_PLAY_WATCH_FOR_CALL_BACK_NOT_STARTED = 166,       // Plug-and-play monitoring is not activated yet (0xa6)
    RW_PLUG_AND_PLAY_WATCH_FOR_CALL_BACK_ALREADY_STARTED = 167,   // Plug-and-play monitoring is activated already (0xa7)
    RW_WINDOW_CLASS_OF_PLUG_AND_PLAY_REGISTRATION_ERROR = 168,    // Failed to register the plug-and-play monitoring window class (0xa8)
    RW_WINDOW_OF_PLUG_AND_PLAY_CREATE_ERROR = 169,                // Failed to create the plug-and-play monitoring window (0xa9)
    RW_GUID_DEVICE_INFORMATION_SET_ERROR = 170,                   // The handle to the GUID device information set cannot be acquired (0xaa)
    RW_GUID_INTERFACE_DATA_ERROR = 171,                           // The GUID interface data cannot be acquired (0xab)
    RW_GUID_SYMBOLIC_DATA_ERROR = 172,                            // The GUID symbolic name cannot be acquired (0xac)
    RW_API_NOT_IMPLEMENTED_FOR_THIS_PLATFORM = 173,               // This is the API that is not installed in this OS (0xad)
    RW_API_NOT_IMPLEMENTED_FOR_THIS_PLATHOME
        = RW_API_NOT_IMPLEMENTED_FOR_THIS_PLATFORM,               // This is the API that is not installed in this OS (0xad)
    RW_REQUEST_SYSTEM_CODE_ERROR = 174,                           // Failed to acquire the system code list of the card (0xae)
    RW_SEARCH_SERVICE_CODE_ERROR = 175,                           // Failed to acquire the service code list of the card (0xaf)
    RW_USB_COMMUNICATION_ERROR = 176,                             // Error has occured at USB communication (0xb0)
    RW_READER_WRITER_DISCONNECTED = 177,                          // Reader/Writer is disconnected (0xb1)
    RW_NO_SYSTEM_RESOURCES_ERROR = 178,                           // Failed in reserving system resource at driver (0xb2)
    RW_COMMAND_CHECKSUM_ERROR = 179,                              // Check sum error has occured in command packet (0xb3)
    RW_COMMAND_IDTR_ERROR = 180,                                  // Illegal Transaction ID is detected (0xb4)
    RW_READER_WRITER_MODE_ERROR = 181,                            // Specified command has not been executed cause of Reader/Writer mode (0xb5)
    RW_INVALID_COMMAND_PACKET_PARAMETER = 182,                    // Parameter error occured in command packet (0xb6)
    RW_INVALID_COMMAND_CODE = 183,                                // Command code is illegal (0xb7)
    RW_READER_WRITER_VERSION_MISMATCH = 184,                      // Error has occured in model determination process of Reader/Writer (0xb8)
    RW_ILLEGAL_COMMAND_PACKET = 185,                              // Command packet header or footer is illegal (0xb9)
    RW_READER_WRITER_UNIT_NUMBER_ERROR = 186,                     // Specified unit number of the Reader/Writer is wrong (0xba)
    RW_LOCK_TIMEOUT = 187,                                        // A Reader/Writer access right acquisition timeout occurred (0xbb)
    RW_GET_ACCESS_AUTHORITY_ERROR = 188,                          // A transaction-level access right (lock) could not be acquired (0xbc)
    RW_READER_WRITER_VERSION_UNSUPPORTED = 189,                   // The Reader/Writer model is not supported (0xbd)
    RW_LIBRARY_IS_INVALID = 190,                                  // The library file is invalid (0xbe)
	RW_MODE_TRANSMIT_ERROR = 191,								  // An error occurred in the device setting sequence for a mode transition (0xbf)
	RW_DEVICE_INITIALIZE_ERROR = 192,							  // An error occurred in device initialization (0xc0)
	RW_TEMPERATURE_ERROR = 193,									  // The device temperature is abnormal (0xc1)
	RW_TEMPERATURE_FATAL_ERROR = 194,							  // The device is unavailable due to an abnormal temperature (0xc2)
	RW_TARGET_DEVICE_NOT_READY = 195,							  // The target device is not ready (0xc3)
	RW_READER_WRITER_POWER_DOWNED = 196,						  // The reader/writer is turned off (0xc4)
	RW_RADER_WRITER_POWER_DOWNED =
		RW_READER_WRITER_POWER_DOWNED

#ifdef __cplusplus
};
#else if
}enumeration_rw_error_type;
#endif


/*
100 = Error has not occurred.
101 = Undefined error
102 = Argument of the function is illegal.
103 = Cannot secure the memory space.
104 = Failed in creating the thread.
105 = The library is not initialized.
106 = The library is already initialized.
107 = An illegal name is specified.
108 = Cannot find the file.
109 = Cannot open the file.
110 = The file is not opened yet.
111 = The file is already opened.
112 = An illegal directory name is specified.
113 = Cannot find the directory.
114 = Cannot open the directory,
115 = The directory is not opened yet.
116 = The directory is already opened.
117 = An illegal port name is specified.
118 = Cannot find the port.
119 = Cannot open the port.
120 = The port is not opened yet.
121 = The port is already opened.
122 = The time-out value is illegal.
123 = The baud rate value is illegal.
124 = Home directory of plug-in is not set.
125 = Cannot find the home directory of plug-in.
126 = Failed in initializing the plug-in.
127 = Cannot find the plug-in.
128 = Cannot find the command plug-in.
129 = Cannot find the device plug-in.
130 = Cannot find the utility plug-in.
131 = Failed in accessing the table.
132 = Cannot find the command.
133 = Failed in executing the script.
134 = Failed in initializing the port.
135 = Failed in setting time-out of the port.
136 = Device control setup of the port is illegal.
137 = Failed in masking the port.
138 = Failed in purging the port.
139 = Failed in acquisition of plain text data.
140 = Failed in saving the plain text data.
141 = Failed in acquisition of cipher text data.
142 = Failed in saving the cipher text data.
143 = The random number sequence required for authentication is not set.
144 = Transaction ID is not set.
145 = Failed in acquiring the transaction key that is required for data encryption.
146 = The transaction key required for data encryption is illegal.
147 = Un-matching is found in the communication parity check.
148 = Received NACK from the Reader/Writer.
149 = Syntax error is notified from the Reader/Writer.
150 = Received illegal packet from Reader/Writer.
151 = Number of times of sequence has exceeded what can be sent by a single session.
152 = No response is returned from the Reader/Writer.
153 = Failed in sending data to the Reader/Writer.
154 = Time-out occurred when sending data to the Reader/Writer.
155 = Failed in receiving data from the Reader/Writer.
156 = Time-out occurred when receiving data from the Reader/Writer.
157 = Could not capture the card.
158 = Could not obtained the card information because of illegal index of the card.
159 = Received the error status flag from the card.
160 = No response is returned to the Communicate Thru command.
161 = The method to specify the user key is incorrect
162 = Duration of use is already expired
163 = Callback parameter is not set
164 = Failed to register the message that shall be sent when Reader/Writer is connected
165 = Failed to register the message that shall be sent when Reader/Writer is disconnected
166 = Plug-and-play monitoring is not activated yet
167 = Plug-and-play monitoring is activated already
168 = Failed to register the plug-and-play monitoring window class
169 = Failed to create the plug-and-play monitoring window
170 = The handle to the GUID device information set cannot be acquired
171 = The GUID interface data cannot be acquired
172 = The GUID symbolic name cannot be acquired
173 = This is the API that is not installed in this OS
174 = Failed to acquire the system code list of the card
175 = Failed to acquire the service code list of the card
176 = Error has occured at USB communication
177 = Reader/Writer is disconnected
178 = Failed in reserving system resource at driver
179 = Check sum error has occured in command packet
180 = Illegal Transaction ID is detected
181 = Specified command has not been executed cause of Reader/Writer mode
182 = Parameter error occured in command packet
183 = Command code is illegal
184 = Error has occured in model determination process of Reader/Writer
185 = Command packet header or footer is illegal
186 = Specified unit number of the Reader/Writer is wrong
187 = A Reader/Writer access right acquisition timeout occurred
188 = A transaction-level access right (lock) could not be acquired
189 = The Reader/Writer model is not supported
190 = The library file is invalid
191 = An error occurred in the device setting sequence for a mode transition
192 = An error occurred in device initialization
193 = The device temperature is abnormal
194 = The device is unavailable due to an abnormal temperature
195 = The target device is not ready
196 = The reader/writer is turned off

*/

typedef enumeration_rw_error_type enumernation_rw_error_type;

#endif // RW_ERROR_H
